#![forbid(unsafe_code)]
#![deny(missing_docs)]

//! Quest workspace validation and review primitives shared by editor hosts.

pub mod orchestrator;
pub mod runtime;

use std::{
    collections::{BTreeMap, HashSet},
    path::{Path, PathBuf},
    process::Command,
    time::Duration,
};

use engine_core::{EngineConfig, EngineError, EngineResult};
use runtime_min::headless_services_from_scene;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Quest specification generated by an AI model.
#[derive(Debug)]
pub struct GeneratedQuestSpec {
    /// Short Quest title.
    pub title: String,
    /// Editable Markdown specification body.
    pub spec: String,
    /// Initial execution or investigation tasks.
    pub tasks: Vec<GeneratedQuestTask>,
    /// Interactive clarification question cards.
    pub question_cards: Vec<GeneratedQuestionCard>,
}

/// Task generated for a Quest timeline.
#[derive(Debug)]
pub struct GeneratedQuestTask {
    /// Task title.
    pub title: String,
    /// Optional task context.
    pub summary: Option<String>,
    /// Task-specific acceptance checks.
    pub acceptance: Vec<String>,
}

/// Interactive question card generated for Quest clarification.
#[derive(Debug)]
pub struct GeneratedQuestionCard {
    /// Card title.
    pub title: String,
    /// Questions shown on the card.
    pub questions: Vec<GeneratedQuestion>,
}

/// One generated clarification question.
#[derive(Debug)]
pub struct GeneratedQuestion {
    /// Stable question id.
    pub id: String,
    /// User-facing question prompt.
    pub prompt: String,
    /// Selectable options for the question.
    pub options: Vec<GeneratedQuestionOption>,
    /// Whether multiple options can be selected.
    pub allow_multiple: bool,
    /// Whether the user may provide a custom answer.
    pub allow_custom: bool,
}

/// One selectable option for a generated clarification question.
#[derive(Debug)]
pub struct GeneratedQuestionOption {
    /// Stable option id.
    pub id: String,
    /// User-facing option label.
    pub label: String,
    /// Optional option explanation.
    pub description: Option<String>,
}

/// Policy-approved Quest validation command metadata.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct QuestValidationCommandSpec {
    /// Stable command id.
    pub id: &'static str,
    /// Display label.
    pub label: &'static str,
    /// Executable name.
    pub program: &'static str,
    /// Static executable arguments.
    pub args: &'static [&'static str],
}

/// A file changed by a Quest execution workspace.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ChangedFile {
    /// Project-relative path.
    pub path: String,
    /// Approximate number of added lines.
    pub additions: u32,
    /// Approximate number of deleted lines.
    pub deletions: u32,
    /// Change status such as `added`, `modified`, or `deleted`.
    pub status: String,
    /// Compact line-oriented diff preview.
    #[serde(default)]
    pub diff: String,
}

/// Result from a Quest validation check.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ValidationResult {
    /// Human-readable validation name.
    pub name: String,
    /// Validation status such as `passed`, `failed`, or `skipped`.
    pub status: String,
    /// Short user-facing summary.
    pub summary: String,
    /// Policy registry command id, when command-backed.
    #[serde(default)]
    pub command_id: Option<String>,
    /// Display command, when command-backed.
    #[serde(default)]
    pub command: Option<String>,
    /// Whether the command came from the policy-approved registry.
    #[serde(default)]
    pub policy_approved: bool,
    /// Captured stdout/stderr for command-backed validations.
    #[serde(default)]
    pub log: String,
}

impl ValidationResult {
    /// Creates a validation result.
    pub fn new(
        name: impl Into<String>,
        status: impl Into<String>,
        summary: impl Into<String>,
    ) -> Self {
        Self {
            name: name.into(),
            status: status.into(),
            summary: summary.into(),
            command_id: None,
            command: None,
            policy_approved: false,
            log: String::new(),
        }
    }

    /// Attaches policy-approved command evidence to this result.
    pub fn with_policy_command(
        mut self,
        command_id: impl Into<String>,
        command: impl Into<String>,
        log: impl Into<String>,
    ) -> Self {
        self.command_id = Some(command_id.into());
        self.command = Some(command.into());
        self.policy_approved = true;
        self.log = log.into();
        self
    }
}

/// Parses Quest creation model output into a structured Quest spec.
pub fn parse_generated_quest_response(
    tool_calls: &[engine_ai::ToolCall],
    text_content: &str,
    goal: &str,
) -> EngineResult<GeneratedQuestSpec> {
    let mut spec_artifact: Option<(String, String)> = None;
    let mut tasks = Vec::new();
    let mut question_cards = Vec::new();
    for call in tool_calls {
        match call.name.as_str() {
            "create_or_update_spec" => {
                let title = call
                    .arguments
                    .get("title")
                    .and_then(Value::as_str)
                    .unwrap_or_default()
                    .trim()
                    .trim_matches(['"', '\'', '`', '.', ':', '#', '*'])
                    .trim()
                    .chars()
                    .take(96)
                    .collect::<String>();
                let spec = call
                    .arguments
                    .get("markdown")
                    .and_then(Value::as_str)
                    .unwrap_or_default()
                    .trim()
                    .to_owned();
                if title.is_empty() {
                    return Err(EngineError::config(
                        "Quest spec tool call must include a non-empty title",
                    ));
                }
                if spec.is_empty() {
                    return Err(EngineError::config(
                        "Quest spec tool call must include non-empty markdown",
                    ));
                }
                spec_artifact = Some((title, spec));
            }
            "create_task" => {
                let title = call
                    .arguments
                    .get("title")
                    .and_then(Value::as_str)
                    .unwrap_or_default()
                    .trim()
                    .to_owned();
                if title.is_empty() {
                    return Err(EngineError::config(
                        "Quest task tool call must include a non-empty title",
                    ));
                }
                let summary = call
                    .arguments
                    .get("summary")
                    .and_then(Value::as_str)
                    .map(str::trim)
                    .filter(|value| !value.is_empty())
                    .map(str::to_owned);
                let acceptance = call
                    .arguments
                    .get("acceptance")
                    .and_then(Value::as_array)
                    .map(|items| {
                        items
                            .iter()
                            .filter_map(Value::as_str)
                            .map(str::trim)
                            .filter(|value| !value.is_empty())
                            .map(str::to_owned)
                            .collect::<Vec<_>>()
                    })
                    .unwrap_or_default();
                tasks.push(GeneratedQuestTask {
                    title,
                    summary,
                    acceptance,
                });
            }
            "ask_questions" => {
                let title = call
                    .arguments
                    .get("title")
                    .and_then(Value::as_str)
                    .map(str::trim)
                    .filter(|value| !value.is_empty())
                    .unwrap_or("Questions")
                    .chars()
                    .take(96)
                    .collect::<String>();
                let questions_value = call
                    .arguments
                    .get("questions")
                    .and_then(Value::as_array)
                    .ok_or_else(|| {
                        EngineError::config("Quest question tool call must include questions")
                    })?;
                let mut questions = Vec::new();
                for (question_index, question_value) in questions_value.iter().enumerate() {
                    let prompt = question_value
                        .get("prompt")
                        .and_then(Value::as_str)
                        .unwrap_or_default()
                        .trim()
                        .to_owned();
                    if prompt.is_empty() {
                        return Err(EngineError::config(
                            "Quest question tool call includes an empty prompt",
                        ));
                    }
                    let id = question_value
                        .get("id")
                        .and_then(Value::as_str)
                        .map(str::trim)
                        .filter(|value| !value.is_empty())
                        .map(str::to_owned)
                        .unwrap_or_else(|| format!("q{}", question_index + 1));
                    let allow_multiple = question_value
                        .get("allow_multiple")
                        .and_then(Value::as_bool)
                        .unwrap_or(false);
                    let allow_custom = question_value
                        .get("allow_custom")
                        .and_then(Value::as_bool)
                        .unwrap_or(true);
                    let options = question_value
                        .get("options")
                        .and_then(Value::as_array)
                        .map(|items| {
                            items
                                .iter()
                                .enumerate()
                                .filter_map(|(option_index, option_value)| {
                                    let label = option_value
                                        .get("label")
                                        .and_then(Value::as_str)
                                        .unwrap_or_default()
                                        .trim();
                                    if label.is_empty() {
                                        return None;
                                    }
                                    let id = option_value
                                        .get("id")
                                        .and_then(Value::as_str)
                                        .map(str::trim)
                                        .filter(|value| !value.is_empty())
                                        .map(str::to_owned)
                                        .unwrap_or_else(|| {
                                            char::from(b'A' + option_index.min(25) as u8)
                                                .to_string()
                                        });
                                    let description = option_value
                                        .get("description")
                                        .and_then(Value::as_str)
                                        .map(str::trim)
                                        .filter(|value| !value.is_empty())
                                        .map(str::to_owned);
                                    Some(GeneratedQuestionOption {
                                        id,
                                        label: label.to_owned(),
                                        description,
                                    })
                                })
                                .collect::<Vec<_>>()
                        })
                        .unwrap_or_default();
                    if options.is_empty() && !allow_custom {
                        return Err(EngineError::config(
                            "Quest question without options must allow a custom answer",
                        ));
                    }
                    questions.push(GeneratedQuestion {
                        id,
                        prompt,
                        options,
                        allow_multiple,
                        allow_custom,
                    });
                }
                if questions.is_empty() {
                    return Err(EngineError::config(
                        "Quest question tool call must include at least one question",
                    ));
                }
                question_cards.push(GeneratedQuestionCard { title, questions });
            }
            other => {
                return Err(EngineError::config(format!(
                    "unsupported Quest creation tool call: {other}"
                )));
            }
        }
    }
    let (title, spec) = if let Some(spec_artifact) = spec_artifact {
        spec_artifact
    } else {
        let spec = text_content.trim();
        if spec.is_empty() {
            (
                quest_title_from_goal(goal),
                format!(
                    "# {}\n\n## Goal\n\n{}\n",
                    quest_title_from_goal(goal),
                    goal.trim()
                ),
            )
        } else {
            (
                quest_title_from_markdown_or_goal(spec, goal),
                spec.to_owned(),
            )
        }
    };
    Ok(GeneratedQuestSpec {
        title,
        spec,
        tasks,
        question_cards,
    })
}

/// Builds a Quest title from a free-form user goal.
pub fn quest_title_from_goal(goal: &str) -> String {
    let title = goal
        .lines()
        .find(|line| !line.trim().is_empty())
        .unwrap_or("Untitled Quest")
        .trim()
        .trim_matches(['"', '\'', '`', '.', ':', '#', '*'])
        .trim()
        .chars()
        .take(96)
        .collect::<String>();
    if title.is_empty() {
        "Untitled Quest".to_owned()
    } else {
        title
    }
}

/// Extracts a Quest title from Markdown or falls back to the user goal.
pub fn quest_title_from_markdown_or_goal(markdown: &str, goal: &str) -> String {
    markdown
        .lines()
        .find_map(|line| line.trim().strip_prefix("# "))
        .map(str::trim)
        .filter(|title| !title.is_empty())
        .map(|title| title.chars().take(96).collect::<String>())
        .unwrap_or_else(|| quest_title_from_goal(goal))
}

/// Returns the AI tool definitions used for Quest creation.
pub fn quest_creation_tool_definitions() -> Vec<engine_ai::ToolDefinition> {
    vec![
        engine_ai::ToolDefinition {
            name: "create_or_update_spec".to_owned(),
            description: "Create the editable Markdown specification for the Quest.".to_owned(),
            parameters: serde_json::json!({
                "type": "object",
                "additionalProperties": false,
                "required": ["title", "markdown"],
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "Short Quest title."
                    },
                    "markdown": {
                        "type": "string",
                        "description": "Editable Markdown spec. Choose sections that fit the goal; do not force a fixed template."
                    }
                }
            }),
        },
        engine_ai::ToolDefinition {
            name: "create_task".to_owned(),
            description:
                "Create one flexible execution or investigation task for the Quest timeline."
                    .to_owned(),
            parameters: serde_json::json!({
                "type": "object",
                "additionalProperties": false,
                "required": ["title"],
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "Task title."
                    },
                    "summary": {
                        "type": "string",
                        "description": "Optional context or intent for this task."
                    },
                    "acceptance": {
                        "type": "array",
                        "items": { "type": "string" },
                        "description": "Optional task-specific acceptance checks."
                    }
                }
            }),
        },
        engine_ai::ToolDefinition {
            name: "ask_questions".to_owned(),
            description:
                "Create an interactive question card when user clarification is needed before a useful Quest spec can be finalized."
                    .to_owned(),
            parameters: serde_json::json!({
                "type": "object",
                "additionalProperties": false,
                "required": ["questions"],
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "Short card title, for example Questions."
                    },
                    "questions": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "required": ["prompt"],
                            "properties": {
                                "id": {
                                    "type": "string",
                                    "description": "Stable question id."
                                },
                                "prompt": {
                                    "type": "string",
                                    "description": "Question shown to the user."
                                },
                                "allow_multiple": {
                                    "type": "boolean",
                                    "description": "Whether multiple options can be selected."
                                },
                                "allow_custom": {
                                    "type": "boolean",
                                    "description": "Whether the user may type a custom answer."
                                },
                                "options": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "additionalProperties": false,
                                        "required": ["label"],
                                        "properties": {
                                            "id": {
                                                "type": "string",
                                                "description": "Stable option id such as A, B, C."
                                            },
                                            "label": {
                                                "type": "string",
                                                "description": "Option label."
                                            },
                                            "description": {
                                                "type": "string",
                                                "description": "Optional explanation for this option."
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }),
        },
    ]
}

/// Captures all non-generated project files in a workspace.
pub fn collect_workspace_snapshot(root: &Path) -> EngineResult<BTreeMap<String, Vec<u8>>> {
    let mut files = BTreeMap::new();
    collect_workspace_snapshot_inner(root, root, &mut files)?;
    Ok(files)
}

fn collect_workspace_snapshot_inner(
    root: &Path,
    current: &Path,
    files: &mut BTreeMap<String, Vec<u8>>,
) -> EngineResult<()> {
    const SKIPPED_DIRS: &[&str] = &[".git", "target", "dist", "node_modules"];
    if !current.exists() {
        return Ok(());
    }
    for entry in std::fs::read_dir(current).map_err(|source| EngineError::Filesystem {
        path: current.to_path_buf(),
        source,
    })? {
        let entry = entry.map_err(|source| EngineError::Filesystem {
            path: current.to_path_buf(),
            source,
        })?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|source| EngineError::Filesystem {
                path: path.clone(),
                source,
            })?;
        if file_type.is_dir() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if SKIPPED_DIRS.iter().any(|skipped| *skipped == name) {
                continue;
            }
            collect_workspace_snapshot_inner(root, &path, files)?;
        } else if file_type.is_file() {
            let relative = path
                .strip_prefix(root)
                .unwrap_or(&path)
                .to_string_lossy()
                .replace('\\', "/");
            let bytes = std::fs::read(&path).map_err(|source| EngineError::Filesystem {
                path: path.clone(),
                source,
            })?;
            files.insert(relative, bytes);
        }
    }
    Ok(())
}

/// Diffs two Quest workspace snapshots into reviewable changed files.
pub fn diff_workspace_snapshots(
    before: &BTreeMap<String, Vec<u8>>,
    after: &BTreeMap<String, Vec<u8>>,
) -> Vec<ChangedFile> {
    let mut changed = Vec::new();
    for (path, after_bytes) in after {
        match before.get(path) {
            Some(before_bytes) if before_bytes == after_bytes => {}
            Some(before_bytes) => changed.push(ChangedFile {
                path: path.clone(),
                additions: count_added_lines(before_bytes, after_bytes),
                deletions: count_added_lines(after_bytes, before_bytes),
                status: "modified".to_owned(),
                diff: format_line_diff(path, Some(before_bytes), Some(after_bytes)),
            }),
            None => changed.push(ChangedFile {
                path: path.clone(),
                additions: String::from_utf8_lossy(after_bytes).lines().count() as u32,
                deletions: 0,
                status: "added".to_owned(),
                diff: format_line_diff(path, None, Some(after_bytes)),
            }),
        }
    }
    for (path, before_bytes) in before {
        if !after.contains_key(path) {
            changed.push(ChangedFile {
                path: path.clone(),
                additions: 0,
                deletions: String::from_utf8_lossy(before_bytes).lines().count() as u32,
                status: "deleted".to_owned(),
                diff: format_line_diff(path, Some(before_bytes), None),
            });
        }
    }
    changed
}

fn format_line_diff(path: &str, before: Option<&[u8]>, after: Option<&[u8]>) -> String {
    let mut output = String::new();
    output.push_str(&format!("--- a/{path}\n+++ b/{path}\n"));
    match (before, after) {
        (Some(before), Some(after)) => {
            let before_text = String::from_utf8_lossy(before);
            let after_text = String::from_utf8_lossy(after);
            let before_lines: HashSet<&str> = before_text.lines().collect();
            let after_lines: HashSet<&str> = after_text.lines().collect();
            for line in before_text
                .lines()
                .filter(|line| !after_lines.contains(line))
                .take(80)
            {
                output.push_str(&format!("-{line}\n"));
            }
            for line in after_text
                .lines()
                .filter(|line| !before_lines.contains(line))
                .take(80)
            {
                output.push_str(&format!("+{line}\n"));
            }
        }
        (None, Some(after)) => {
            for line in String::from_utf8_lossy(after).lines().take(120) {
                output.push_str(&format!("+{line}\n"));
            }
        }
        (Some(before), None) => {
            for line in String::from_utf8_lossy(before).lines().take(120) {
                output.push_str(&format!("-{line}\n"));
            }
        }
        (None, None) => {}
    }
    output
}

fn count_added_lines(before: &[u8], after: &[u8]) -> u32 {
    let before_text = String::from_utf8_lossy(before);
    let after_text = String::from_utf8_lossy(after);
    let before_lines: HashSet<&str> = before_text.lines().collect();
    after_text
        .lines()
        .filter(|line| !before_lines.contains(line))
        .count() as u32
}

/// Runs the standard Quest validation suite for a workspace root.
pub fn validate_quest_workspace(workspace_root: &Path) -> Vec<ValidationResult> {
    let mut results = Vec::new();
    let project = match engine_editor::ProjectContext::open(workspace_root) {
        Ok(project) => {
            results.push(ValidationResult::new(
                "Project load",
                "passed",
                "Project manifest, default scene, and asset database loaded.",
            ));
            project
        }
        Err(error) => {
            results.push(ValidationResult::new(
                "Project load",
                "failed",
                error.to_string(),
            ));
            return results;
        }
    };

    results.push(validate_quest_scene_round_trip(&project));
    results.push(validate_quest_asset_scan(&project));
    results.push(validate_quest_script_references(&project));
    results.push(validate_quest_play_preview(workspace_root, &project));

    let cargo_toml = workspace_root.join("Cargo.toml");
    if cargo_toml.is_file() {
        let command = quest_validation_command_specs()
            .into_iter()
            .find(|command| command.id == "cargo_check_quiet")
            .expect("quest validation registry must include cargo_check_quiet");
        match command.run(workspace_root) {
            Ok(output) if output.status.success() => results.push(
                ValidationResult::new(
                    command.label,
                    "passed",
                    format!(
                        "{} completed successfully through policy-approved registry entry `{}`.",
                        command.display(),
                        command.id
                    ),
                )
                .with_policy_command(
                    command.id,
                    command.display(),
                    command_output_log(&output),
                ),
            ),
            Ok(output) => {
                let log = command_output_log(&output);
                let summary = log.lines().take(12).collect::<Vec<_>>().join("\n");
                results.push(
                    ValidationResult::new(command.label, "failed", summary).with_policy_command(
                        command.id,
                        command.display(),
                        log,
                    ),
                );
            }
            Err(error) => results.push(
                ValidationResult::new(
                    command.label,
                    "failed",
                    format!("failed to run {}: {error}", command.display()),
                )
                .with_policy_command(
                    command.id,
                    command.display(),
                    error.to_string(),
                ),
            ),
        }
    } else {
        results.push(ValidationResult::new(
            "cargo check",
            "skipped",
            "No Cargo.toml found in Quest workspace.",
        ));
    }
    results
}

fn validate_quest_scene_round_trip(project: &engine_editor::ProjectContext) -> ValidationResult {
    match project
        .scene
        .to_json("quest-validation")
        .and_then(|scene_json| engine_ecs::Scene::from_json(&scene_json).map(|_| scene_json))
    {
        Ok(scene_json) => ValidationResult::new(
            "Scene schema",
            "passed",
            format!(
                "Default scene round-tripped through the ECS JSON schema ({} bytes).",
                scene_json.len()
            ),
        ),
        Err(error) => ValidationResult::new("Scene schema", "failed", error.to_string()),
    }
}

fn validate_quest_asset_scan(project: &engine_editor::ProjectContext) -> ValidationResult {
    let assets = project.sorted_assets();
    let missing = assets
        .iter()
        .filter(|asset| {
            !project
                .root
                .join(&project.manifest.asset_root)
                .join(&asset.source_path)
                .is_file()
        })
        .map(|asset| asset.source_path.display().to_string())
        .take(8)
        .collect::<Vec<_>>();
    if missing.is_empty() {
        ValidationResult::new(
            "Asset scan",
            "passed",
            format!(
                "Asset database scanned {} supported asset(s).",
                assets.len()
            ),
        )
    } else {
        ValidationResult::new(
            "Asset scan",
            "failed",
            format!(
                "Asset metadata points at missing source files: {}",
                missing.join(", ")
            ),
        )
    }
}

fn validate_quest_script_references(project: &engine_editor::ProjectContext) -> ValidationResult {
    let mut script_refs = Vec::new();
    for (_, object) in project.scene.objects() {
        for script in &object.scripts {
            if !script.source.trim().is_empty() {
                script_refs.push(script.source.clone());
            }
        }
        for component in &object.components {
            if let engine_ecs::ComponentData::Script(script) = component {
                if !script.source.trim().is_empty() {
                    script_refs.push(script.source.clone());
                }
            }
        }
    }
    script_refs.sort();
    script_refs.dedup();
    let missing = script_refs
        .iter()
        .filter(|script| !resolve_project_script_reference(project, script).is_file())
        .take(8)
        .cloned()
        .collect::<Vec<_>>();
    if missing.is_empty() {
        ValidationResult::new(
            "Script references",
            "passed",
            format!("Validated {} scene script reference(s).", script_refs.len()),
        )
    } else {
        ValidationResult::new(
            "Script references",
            "failed",
            format!("Missing script reference(s): {}", missing.join(", ")),
        )
    }
}

fn resolve_project_script_reference(
    project: &engine_editor::ProjectContext,
    script: &str,
) -> PathBuf {
    let script = script.strip_prefix("project:/").unwrap_or(script);
    let script_path = Path::new(script);
    if script_path.is_absolute() {
        script_path.to_path_buf()
    } else {
        let project_path = project.root.join(script_path);
        if project_path.is_file() {
            return project_path;
        }
        for script_root in &project.manifest.script_roots {
            let candidate = project.root.join(script_root).join(script_path);
            if candidate.is_file() {
                return candidate;
            }
        }
        project_path
    }
}

fn validate_quest_play_preview(
    workspace_root: &Path,
    project: &engine_editor::ProjectContext,
) -> ValidationResult {
    match headless_services_from_scene(
        EngineConfig::default(),
        workspace_root.to_path_buf(),
        &project.scene,
    )
    .and_then(|mut services| {
        services.set_script_roots(
            project
                .manifest
                .script_roots
                .iter()
                .map(|root| PathBuf::from(root.as_str())),
        );
        services.load_project_assets(project.root.join(&project.manifest.asset_root))?;
        services.tick_game_frame(Duration::from_millis(16), true)?;
        Ok(services.diagnostics)
    }) {
        Ok(diagnostics) => {
            let errors = diagnostics
                .iter()
                .filter(|diagnostic| diagnostic.level == "error")
                .take(5)
                .map(|diagnostic| diagnostic.message.clone())
                .collect::<Vec<_>>();
            if errors.is_empty() {
                ValidationResult::new(
                    "Play preview smoke",
                    "passed",
                    format!(
                        "Headless runtime advanced one frame with {} diagnostic(s).",
                        diagnostics.len()
                    ),
                )
            } else {
                ValidationResult::new("Play preview smoke", "failed", errors.join("\n"))
            }
        }
        Err(error) => ValidationResult::new("Play preview smoke", "failed", error.to_string()),
    }
}

fn command_output_log(output: &std::process::Output) -> String {
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    let mut lines = Vec::new();
    if !stdout.trim().is_empty() {
        lines.push("stdout:".to_owned());
        lines.extend(stdout.lines().map(str::to_owned));
    }
    if !stderr.trim().is_empty() {
        lines.push("stderr:".to_owned());
        lines.extend(stderr.lines().map(str::to_owned));
    }
    if lines.is_empty() {
        "Command completed without stdout or stderr.".to_owned()
    } else {
        lines.join("\n")
    }
}

impl QuestValidationCommandSpec {
    fn display(&self) -> String {
        std::iter::once(self.program)
            .chain(self.args.iter().copied())
            .collect::<Vec<_>>()
            .join(" ")
    }

    fn run(&self, workspace_root: &Path) -> EngineResult<std::process::Output> {
        let command: Vec<&str> = std::iter::once(self.program)
            .chain(self.args.iter().copied())
            .collect();
        if command
            != std::iter::once("cargo")
                .chain(["check", "--quiet"])
                .collect::<Vec<_>>()
        {
            return Err(EngineError::config(format!(
                "Quest validation command `{}` is not policy-approved",
                self.display()
            )));
        }
        Command::new(self.program)
            .args(self.args)
            .current_dir(workspace_root)
            .output()
            .map_err(|source| EngineError::Filesystem {
                path: workspace_root.to_path_buf(),
                source,
            })
    }
}

/// Returns policy-approved validation commands for Quest workspaces.
pub fn quest_validation_command_specs() -> Vec<QuestValidationCommandSpec> {
    vec![QuestValidationCommandSpec {
        id: "cargo_check_quiet",
        label: "cargo check",
        program: "cargo",
        args: &["check", "--quiet"],
    }]
}

/// Creates an isolated Quest workspace, using a Git worktree when possible.
pub fn prepare_isolated_workspace(
    project_root: &Path,
    workspace_root: &Path,
    fallback_branch_suffix: impl FnOnce() -> String,
) -> EngineResult<()> {
    if let Some(parent) = workspace_root.parent() {
        std::fs::create_dir_all(parent).map_err(|source| EngineError::Filesystem {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    if try_create_git_worktree(project_root, workspace_root, fallback_branch_suffix)? {
        return Ok(());
    }
    copy_project_tree(project_root, workspace_root)
}

fn try_create_git_worktree(
    project_root: &Path,
    workspace_root: &Path,
    fallback_branch_suffix: impl FnOnce() -> String,
) -> EngineResult<bool> {
    let inside_git = Command::new("git")
        .arg("-C")
        .arg(project_root)
        .arg("rev-parse")
        .arg("--is-inside-work-tree")
        .output();
    let Ok(inside_git) = inside_git else {
        return Ok(false);
    };
    if !inside_git.status.success() {
        return Ok(false);
    }

    let branch = workspace_root
        .file_name()
        .and_then(|value| value.to_str())
        .map(|name| format!("quest/{name}"))
        .unwrap_or_else(|| format!("quest/workspace-{}", fallback_branch_suffix()));
    let output = Command::new("git")
        .arg("-C")
        .arg(project_root)
        .arg("worktree")
        .arg("add")
        .arg("-b")
        .arg(&branch)
        .arg(workspace_root)
        .arg("HEAD")
        .output()
        .map_err(|source| EngineError::Filesystem {
            path: project_root.to_path_buf(),
            source,
        })?;
    Ok(output.status.success())
}

fn copy_project_tree(source: &Path, destination: &Path) -> EngineResult<()> {
    const SKIPPED_DIRS: &[&str] = &[
        ".git",
        "target",
        "dist",
        "node_modules",
        ".ralph-tui",
        ".reasonix",
    ];
    std::fs::create_dir_all(destination).map_err(|source| EngineError::Filesystem {
        path: destination.to_path_buf(),
        source,
    })?;
    for entry in std::fs::read_dir(source).map_err(|source_error| EngineError::Filesystem {
        path: source.to_path_buf(),
        source: source_error,
    })? {
        let entry = entry.map_err(|source_error| EngineError::Filesystem {
            path: source.to_path_buf(),
            source: source_error,
        })?;
        let path = entry.path();
        let name = entry.file_name();
        let name_string = name.to_string_lossy();
        if SKIPPED_DIRS.iter().any(|skipped| *skipped == name_string) {
            continue;
        }
        let target = destination.join(&name);
        let file_type = entry
            .file_type()
            .map_err(|source_error| EngineError::Filesystem {
                path: path.clone(),
                source: source_error,
            })?;
        if file_type.is_dir() {
            copy_project_tree(&path, &target)?;
        } else if file_type.is_file() {
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent).map_err(|source| EngineError::Filesystem {
                    path: parent.to_path_buf(),
                    source,
                })?;
            }
            std::fs::copy(&path, &target).map_err(|source| EngineError::Filesystem {
                path: target,
                source,
            })?;
        }
    }
    Ok(())
}

/// Captures a rollback snapshot for one active project file.
pub fn snapshot_rollback_file(
    rollback_root: &Path,
    relative: &Path,
    active_file: &Path,
) -> EngineResult<()> {
    let target = rollback_root.join(relative);
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent).map_err(|source| EngineError::Filesystem {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    if active_file.is_file() {
        std::fs::copy(active_file, &target).map_err(|source| EngineError::Filesystem {
            path: target,
            source,
        })?;
    } else {
        let tombstone = target.with_extension(format!(
            "{}missing",
            target
                .extension()
                .and_then(|extension| extension.to_str())
                .map(|extension| format!("{extension}."))
                .unwrap_or_default()
        ));
        std::fs::write(&tombstone, b"").map_err(|source| EngineError::Filesystem {
            path: tombstone,
            source,
        })?;
    }
    Ok(())
}

/// Restores active project files from a rollback snapshot.
pub fn restore_rollback_files(
    rollback_root: &Path,
    project_root: &Path,
    files: &[String],
    normalize_relative_path: impl Fn(&str) -> EngineResult<PathBuf>,
) -> EngineResult<()> {
    for file in files {
        let relative = normalize_relative_path(file)?;
        let snapshot = rollback_root.join(&relative);
        let destination = project_root.join(&relative);
        let tombstone = snapshot.with_extension(format!(
            "{}missing",
            snapshot
                .extension()
                .and_then(|extension| extension.to_str())
                .map(|extension| format!("{extension}."))
                .unwrap_or_default()
        ));
        if tombstone.is_file() {
            if destination.exists() {
                std::fs::remove_file(&destination).map_err(|source| EngineError::Filesystem {
                    path: destination.clone(),
                    source,
                })?;
            }
            continue;
        }
        if !snapshot.is_file() {
            return Err(EngineError::config(format!(
                "rollback file is missing: {file}"
            )));
        }
        if let Some(parent) = destination.parent() {
            std::fs::create_dir_all(parent).map_err(|source| EngineError::Filesystem {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        std::fs::copy(&snapshot, &destination).map_err(|source| EngineError::Filesystem {
            path: destination,
            source,
        })?;
    }
    Ok(())
}
